name: CI

on:
  push:
    branches: 
      - "*"
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          
      - name: Run install dependencies
        run: npm install
  
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:     
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
    
      - name: Run test
        run: npm run test
