name: CI

on:
  push:
    branches: 
      - "*"
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run install dependencies
        run: npm install
  
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:       
      - name: Run test
        run: npm run test
